---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Experiment 1 - Motion

## Early

### First Years

```{r echo=FALSE,warning=FALSE,message=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp1_firstyear_early.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Community

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp1_community_early.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Mechanical Turk

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp1_mturk_early.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

## Late

### First Years

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp1_firstyear_late.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Community

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp1_community_late.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Mechanical Turk

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp1_mturk_late.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```


# Experiment 2 - Brightness

## Early

### First Years

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp2_firstyear_early.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Community

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp2_community_early.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Mechanical Turk

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp2_mturk_early.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

## Late

### First Years

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp2_firstyear_late.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Community

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp2_community_late.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```

### Mechanical Turk

```{r echo=FALSE,warning=FALSE,message=FALSE}
source("dmc/dmc.R")
load_model("lba","lba_B.R")
load("data/derived/extra_samples_exp2_mturk_late.RData")
#gelman.diag.dmc(extra_samples)
#t(simplify2array(effectiveSize.dmc(extra_samples)))
plot.dmc(extra_samples,hyper=T,start=1,end=500)
```
