---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r, results='asis',echo=FALSE,message=FALSE}
library(tidyverse)
source("dmc/dmc.R")
load_model("lba","lba_B.R")
```

Note: The error bars for the model represent the 95% credible interval of the posteror predictive distribution. The error bars for the data represent + or - 1 standard error.

# Experiment 1 - Motion

```{r, results='asis',echo=FALSE,message=FALSE}

for (wave in c('early','late')){
  cat('\n')
  cat(paste('##',wave))
  for (group in c('firstyear','community','mturk')){
    cat('\n')
    cat(paste('####',group))
    #load data for relevant group
    load(paste0("data/derived/extra_samples_exp1_",group,"_",wave,".RData"))
  
    pp = h.post.predict.dmc(extra_samples,save.simulation=T,cores=2)
    
    #plot proportion correct
    sim = do.call(rbind, pp) 
    sim = sim %>%
      mutate(s = rownames(sim),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Coh,Emph,R,reps) %>%
      summarise(count = n()) %>%
      group_by(s,St,Coh,Emph,reps) %>%
      mutate(prop = count/sum(count)) %>%
      group_by(St,Coh,Emph,R,reps) %>%
      summarise(prop = mean(prop)) %>%
      group_by(St,Coh,Emph,R) %>%
      summarise(prop_m = mean(prop),
                prop_l = quantile(prop,0.025),
                prop_u = quantile(prop,0.975),
                source = "Model")
    
    data = lapply(pp, function(x) attr(x, "data"))
    data = do.call(rbind, data) 
    data = data %>%
      mutate(s = rownames(data),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Coh,Emph,R) %>%
      summarise(count = n()) %>%
      group_by(s,St,Coh,Emph) %>%
      mutate(prop = count/sum(count)) %>%
      group_by(St,Coh,Emph,R) %>%
      summarise(prop_m = mean(prop),
                prop_l = NA,#prop_m - sd(prop)/sqrt(n()),
                prop_u = NA,#prop_m + sd(prop)/sqrt(n()),
                source = "Data")
     
    pp_smry =  bind_rows(data,sim) %>%
      ungroup() %>%
      mutate(Coh = factor(Coh,levels=c('c25','c20','c15','c10'),labels=c('Very\nEasy','Easy','Hard','Very\nHard')),
             St = factor(St,levels=c('left','right'),labels=c('Leftward Motion','Rightward Motion')),
             Emph = factor(Emph,levels=c('speed','accuracy'),labels=c('Speed Emphasis','Accuracy Emphasis')))
        
    pp_accuracy = ggplot(data=pp_smry,aes(x=Coh,y=prop_m,group=R,colour=source)) +
        geom_errorbar(aes(ymax = prop_u, ymin = prop_l), width= 0.2) +
        geom_point(pch=21, size=2) +
        geom_line(aes(group=interaction(R,source))) +
        ylab("Response Proportion") + xlab('Difficulty') +
        scale_y_continuous(breaks = seq(0,1,0.25),limits = c(0,1)) +
        facet_grid(Emph~St) #+ theme_minimal()
    
    print(pp_accuracy)   
     
     
    #plot response time distribution
    sim = do.call(rbind, pp) 
    sim = sim %>%
      mutate(s = rownames(sim),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Coh,Emph,R,reps) %>%
      #count number of responses of each type in each condition
      mutate(count = n()) %>%
      #filter out responses that were made less than 5 times
      filter(count >= 5) %>%
      #generate quantiles 
      summarise(q10 = quantile(RT,.1),
                q30 = quantile(RT,.3),
                q50 = quantile(RT,.5),
                q70 = quantile(RT,.7),
                q90 = quantile(RT,.9)) %>%
      gather(key=quantile,value=RT,q10:q90) %>%
      #average across subjects
      group_by(St,Coh,Emph,R,quantile,reps) %>%
      summarise(RT = mean(RT)) %>%
      #get CIs
      group_by(St,Coh,Emph,R,quantile) %>%
      summarise(RT_m = mean(RT),
                RT_l = quantile(RT,0.025),
                RT_u = quantile(RT,0.975),
                source = "Model")  
        
    data = lapply(pp, function(x) attr(x, "data"))
    data = do.call(rbind, data) 
    data = data %>%
      mutate(s = rownames(data),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Coh,Emph,R) %>%
      #count number of responses of each type in each condition
      mutate(count = n()) %>%
      #filter out responses that were made less than 5 times
      filter(count >= 5) %>%
      #generate quantiles 
      summarise(q10 = quantile(RT,.1),
                q30 = quantile(RT,.3),
                q50 = quantile(RT,.5),
                q70 = quantile(RT,.7),
                q90 = quantile(RT,.9)) %>%
      gather(key=quantile,value=RT,q10:q90) %>%
      #average across subjects
      group_by(St,Coh,Emph,R,quantile) %>%
      summarise(RT_m = mean(RT),
                RT_l = NA, #RT_m - sd(RT)/sqrt(n()),
                RT_u = NA, #RT_m + sd(RT)/sqrt(n()),
                source = "Data")  
   
    pp_smry =  bind_rows(data,sim) %>%
      ungroup() %>%
      mutate(Coh = factor(Coh,levels=c('c25','c20','c15','c10'),labels=c('Very\nEasy','Easy','Hard','Very\nHard')),
             St = factor(St,levels=c('left','right'),labels=c('Leftward Motion','Rightward Motion')),
             Emph = factor(Emph,levels=c('speed','accuracy'),labels=c('Speed Emphasis','Accuracy Emphasis')))
        
    pp_rt = ggplot(data=pp_smry,aes(x=Coh,y=RT_m*1000,group=quantile,colour=source)) +
        geom_errorbar(aes(ymax = RT_u*1000, ymin = RT_l*1000), width= 0.2) +
        geom_point(pch=21, size=2) +
        geom_line(aes(group=interaction(quantile,source))) +
        ylab("Response Time (ms)") + xlab('Difficulty') +
        scale_y_continuous(breaks = seq(500,2000,500),limits = c(250,2000)) +
        facet_grid(Emph~St+R) #+ theme_minimal()
    
    print(pp_rt)
    
    save(pp_accuracy,file=paste0("figures/pp_accuracy_exp1_",group,"_",wave,".RData"))
    save(pp_rt,file=paste0("figures/pp_rt_exp1_",group,"_",wave,".RData"))
  }   
}
```
# Experiment 2 - Brightness

```{r, results='asis',echo=FALSE,message=FALSE}

for (wave in c('early','late')){
  cat('\n')
  cat(paste('##',wave))
  for (group in c('firstyear','community','mturk')){
    cat('\n')
    cat(paste('####',group))
    #load data for relevant group
    load(paste0("data/derived/extra_samples_exp2_",group,"_",wave,".RData"))
    pp = h.post.predict.dmc(extra_samples,save.simulation=T,cores=2)
    
    #plot proportion correct
    sim = do.call(rbind, pp) 
    sim = sim %>%
      mutate(s = rownames(sim),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Cont,Emph,R,reps) %>%
      summarise(count = n()) %>%
      group_by(s,St,Cont,Emph,reps) %>%
      mutate(prop = count/sum(count)) %>%
      group_by(St,Cont,Emph,R,reps) %>%
      summarise(prop = mean(prop)) %>%
      group_by(St,Cont,Emph,R) %>%
      summarise(prop_m = mean(prop),
                prop_l = quantile(prop,0.025),
                prop_u = quantile(prop,0.975),
                source = "Model")
    
    data = lapply(pp, function(x) attr(x, "data"))
    data = do.call(rbind, data) 
    data = data %>%
      mutate(s = rownames(data),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Cont,Emph,R) %>%
      summarise(count = n()) %>%
      group_by(s,St,Cont,Emph) %>%
      mutate(prop = count/sum(count)) %>%
      group_by(St,Cont,Emph,R) %>%
      summarise(prop_m = mean(prop),
                prop_l = NA,#prop_m - sd(prop)/sqrt(n()),
                prop_u = NA, #prop_m + sd(prop)/sqrt(n()),
                source = "Data")
     
    pp_smry =  bind_rows(data,sim) %>%
      ungroup() %>%
      mutate(Cont = factor(Cont,levels=c('c05','c04','c03','c02'),labels=c('Very\nEasy','Easy','Hard','Very\nHard')),
             St = factor(St,levels=c('light','dark'),labels=c('Light Patch','Dark Patch')),
             Emph = factor(Emph,levels=c('speed','accuracy'),labels=c('Speed Emphasis','Accuracy Emphasis')))
        

    pp_accuracy = ggplot(data=pp_smry,aes(x=Cont,y=prop_m,group=R,colour=source)) +
        geom_errorbar(aes(ymax = prop_u, ymin = prop_l), width= 0.2) +
        geom_point(pch=21, size=2) +
        geom_line(aes(group=interaction(R,source))) +
        ylab("Response Proportion") + xlab('Difficulty') +
        scale_y_continuous(breaks = seq(0,1,0.25),limits = c(0,1)) +
        facet_grid(Emph~St)  #+ theme_minimal()
    
    print(pp_accuracy)   
     
     
    #plot response time distribution
    sim = do.call(rbind, pp) 
    sim = sim %>%
      mutate(s = rownames(sim),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Cont,Emph,R,reps) %>%
      #count number of responses of each type in each condition
      mutate(count = n()) %>%
      #filter out responses that were made less than 5 times
      filter(count >= 5) %>%
      #generate quantiles 
      summarise(q10 = quantile(RT,.1),
                q30 = quantile(RT,.3),
                q50 = quantile(RT,.5),
                q70 = quantile(RT,.7),
                q90 = quantile(RT,.9)) %>%
      gather(key=quantile,value=RT,q10:q90) %>%
      #average across subjects
      group_by(St,Cont,Emph,R,quantile,reps) %>%
      summarise(RT = mean(RT)) %>%
      #get CIs
      group_by(St,Cont,Emph,R,quantile) %>%
      summarise(RT_m = mean(RT),
                RT_l = quantile(RT,0.025),
                RT_u = quantile(RT,0.975),
                source = "Model")  
        
    data = lapply(pp, function(x) attr(x, "data"))
    data = do.call(rbind, data) 
    data = data %>%
      mutate(s = rownames(data),
             s = gsub("\\..*","",s)) %>%
      group_by(s,St,Cont,Emph,R) %>%
      #count number of responses of each type in each condition
      mutate(count = n()) %>%
      #filter out responses that were made less than 5 times
      filter(count >= 5) %>%
      #generate quantiles 
      summarise(q10 = quantile(RT,.1),
                q30 = quantile(RT,.3),
                q50 = quantile(RT,.5),
                q70 = quantile(RT,.7),
                q90 = quantile(RT,.9)) %>%
      gather(key=quantile,value=RT,q10:q90) %>%
      #average across subjects
      group_by(St,Cont,Emph,R,quantile) %>%
      summarise(RT_m = mean(RT),
                RT_l = NA,#RT_m - sd(RT)/sqrt(n()),
                RT_u = NA,#RT_m + sd(RT)/sqrt(n()),
                source = "Data")  
   
    pp_smry =  bind_rows(data,sim) %>%
      ungroup() %>%
      mutate(Cont = factor(Cont,levels=c('c05','c04','c03','c02'),labels=c('Very\nEasy','Easy','Hard','Very\nHard')),
             St = factor(St,levels=c('light','dark'),labels=c('Light Patch','Dark Patch')),
             Emph = factor(Emph,levels=c('speed','accuracy'),labels=c('Speed Emphasis','Accuracy Emphasis')))
        
    
    pp_rt = ggplot(data=pp_smry,aes(x=Cont,y=RT_m*1000,group=quantile,colour=source)) +
        geom_errorbar(aes(ymax = RT_u*1000, ymin = RT_l*1000), width= 0.2) +
        geom_point(pch=21, size=2) +
        geom_line(aes(group=interaction(quantile,source))) +
        ylab("Response Time (ms)") + xlab('Difficulty') +
        scale_y_continuous(breaks = seq(500,2000,500),limits = c(250,2000)) +
        facet_grid(Emph~St+R) #+ theme_minimal()
    
    print(pp_rt)
    
    save(pp_accuracy,file=paste0("figures/pp_accuracy_exp2_",group,"_",wave,".RData"))
    save(pp_rt,file=paste0("figures/pp_rt_exp2_",group,"_",wave,".RData"))
  
  }
}
```

### Combined Figure ###

```{r eval=FALSE, message=FALSE, include=FALSE, results='asis'}

library(gridExtra)

# g_legend<-function(a.gplot){
#   tmp <- ggplot_gtable(ggplot_build(a.gplot))
#   leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
#   legend <- tmp$grobs[[leg]]
#   return(legend)}

col_titles = c('Early in Semester','Late in Semester')
row_titles = c('Local, Credit','Local, Paid','Online, Paid')

for(exp in 1:2){
  for(var in c('accuracy','rt')){
    
    ctr=0
    pl=list()
    for (wave in c('early','late')){
      for (group in c('firstyear','community','mturk')){
        ctr=ctr+1  
        load(file=paste0("figures/pp_",var,"_exp",exp,"_",group,"_",wave,".RData"))
        if(var=='accuracy'){
               pl[[ctr]] = pp_accuracy + theme(legend.position = 'none')
        }
        if(var=='rt'){
               pl[[ctr]] = pp_rt + theme(legend.position = 'none',
                                         strip.text.x = element_text(size = 8),
                                         axis.text.x = element_text(size = 6))
        }
      }
    }
    
    # Add row titles
    pl[1:3] = lapply(1:3, function(i) arrangeGrob(pl[[i]], left=row_titles[i]))
    
    # Add column titles and lay out plots
    panel = grid.arrange(grobs=lapply(c(1,4), function(i) {
      arrangeGrob(grobs=pl[i:(i+2)], top=col_titles[i/3 + 1], ncol=1)
    }), ncol=2)
    
    ggsave(file=paste0("figures/fits_",var,"_exp",exp,".pdf"),plot=panel,height=34,width=26,units="cm")
           
  }
}



```


